//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentMasterApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class employmentEntities : DbContext
    {
        public employmentEntities()
            : base("name=employmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee_recruit> employee_recruit { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<version> versions { get; set; }
    
        public virtual int employee_recruit_delete(string p_id)
        {
            var p_idParameter = p_id != null ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("employee_recruit_delete", p_idParameter);
        }
    
        public virtual int employee_recruit_insert(string p_Id, Nullable<long> p_intv_no, string p_f_name, string p_m_name, string p_l_name, string p_qualification, string p_school, string p_adr1, string p_adr2, string p_adr3, string p_st_no, string p_st_name, string p_city, string p_state, string p_pin, string p_employment_type, Nullable<System.DateTime> p_interview_date, string p_online_diary_no, string p_dispatch_no, Nullable<System.DateTime> p_join_date, Nullable<System.DateTime> p_dated, string p_gen_applied_post, string p_gen_basic_pay, string p_gen_pay_scale_level, string p_gen_payscale, string p_addhoc_net_salary, string p_addhoc_tenure, Nullable<System.DateTime> p_addhoc_from_date, Nullable<System.DateTime> p_addhoc_to_date)
        {
            var p_IdParameter = p_Id != null ?
                new ObjectParameter("p_Id", p_Id) :
                new ObjectParameter("p_Id", typeof(string));
    
            var p_intv_noParameter = p_intv_no.HasValue ?
                new ObjectParameter("p_intv_no", p_intv_no) :
                new ObjectParameter("p_intv_no", typeof(long));
    
            var p_f_nameParameter = p_f_name != null ?
                new ObjectParameter("p_f_name", p_f_name) :
                new ObjectParameter("p_f_name", typeof(string));
    
            var p_m_nameParameter = p_m_name != null ?
                new ObjectParameter("p_m_name", p_m_name) :
                new ObjectParameter("p_m_name", typeof(string));
    
            var p_l_nameParameter = p_l_name != null ?
                new ObjectParameter("p_l_name", p_l_name) :
                new ObjectParameter("p_l_name", typeof(string));
    
            var p_qualificationParameter = p_qualification != null ?
                new ObjectParameter("p_qualification", p_qualification) :
                new ObjectParameter("p_qualification", typeof(string));
    
            var p_schoolParameter = p_school != null ?
                new ObjectParameter("p_school", p_school) :
                new ObjectParameter("p_school", typeof(string));
    
            var p_adr1Parameter = p_adr1 != null ?
                new ObjectParameter("p_adr1", p_adr1) :
                new ObjectParameter("p_adr1", typeof(string));
    
            var p_adr2Parameter = p_adr2 != null ?
                new ObjectParameter("p_adr2", p_adr2) :
                new ObjectParameter("p_adr2", typeof(string));
    
            var p_adr3Parameter = p_adr3 != null ?
                new ObjectParameter("p_adr3", p_adr3) :
                new ObjectParameter("p_adr3", typeof(string));
    
            var p_st_noParameter = p_st_no != null ?
                new ObjectParameter("p_st_no", p_st_no) :
                new ObjectParameter("p_st_no", typeof(string));
    
            var p_st_nameParameter = p_st_name != null ?
                new ObjectParameter("p_st_name", p_st_name) :
                new ObjectParameter("p_st_name", typeof(string));
    
            var p_cityParameter = p_city != null ?
                new ObjectParameter("p_city", p_city) :
                new ObjectParameter("p_city", typeof(string));
    
            var p_stateParameter = p_state != null ?
                new ObjectParameter("p_state", p_state) :
                new ObjectParameter("p_state", typeof(string));
    
            var p_pinParameter = p_pin != null ?
                new ObjectParameter("p_pin", p_pin) :
                new ObjectParameter("p_pin", typeof(string));
    
            var p_employment_typeParameter = p_employment_type != null ?
                new ObjectParameter("p_employment_type", p_employment_type) :
                new ObjectParameter("p_employment_type", typeof(string));
    
            var p_interview_dateParameter = p_interview_date.HasValue ?
                new ObjectParameter("p_interview_date", p_interview_date) :
                new ObjectParameter("p_interview_date", typeof(System.DateTime));
    
            var p_online_diary_noParameter = p_online_diary_no != null ?
                new ObjectParameter("p_online_diary_no", p_online_diary_no) :
                new ObjectParameter("p_online_diary_no", typeof(string));
    
            var p_dispatch_noParameter = p_dispatch_no != null ?
                new ObjectParameter("p_dispatch_no", p_dispatch_no) :
                new ObjectParameter("p_dispatch_no", typeof(string));
    
            var p_join_dateParameter = p_join_date.HasValue ?
                new ObjectParameter("p_join_date", p_join_date) :
                new ObjectParameter("p_join_date", typeof(System.DateTime));
    
            var p_datedParameter = p_dated.HasValue ?
                new ObjectParameter("p_dated", p_dated) :
                new ObjectParameter("p_dated", typeof(System.DateTime));
    
            var p_gen_applied_postParameter = p_gen_applied_post != null ?
                new ObjectParameter("p_gen_applied_post", p_gen_applied_post) :
                new ObjectParameter("p_gen_applied_post", typeof(string));
    
            var p_gen_basic_payParameter = p_gen_basic_pay != null ?
                new ObjectParameter("p_gen_basic_pay", p_gen_basic_pay) :
                new ObjectParameter("p_gen_basic_pay", typeof(string));
    
            var p_gen_pay_scale_levelParameter = p_gen_pay_scale_level != null ?
                new ObjectParameter("p_gen_pay_scale_level", p_gen_pay_scale_level) :
                new ObjectParameter("p_gen_pay_scale_level", typeof(string));
    
            var p_gen_payscaleParameter = p_gen_payscale != null ?
                new ObjectParameter("p_gen_payscale", p_gen_payscale) :
                new ObjectParameter("p_gen_payscale", typeof(string));
    
            var p_addhoc_net_salaryParameter = p_addhoc_net_salary != null ?
                new ObjectParameter("p_addhoc_net_salary", p_addhoc_net_salary) :
                new ObjectParameter("p_addhoc_net_salary", typeof(string));
    
            var p_addhoc_tenureParameter = p_addhoc_tenure != null ?
                new ObjectParameter("p_addhoc_tenure", p_addhoc_tenure) :
                new ObjectParameter("p_addhoc_tenure", typeof(string));
    
            var p_addhoc_from_dateParameter = p_addhoc_from_date.HasValue ?
                new ObjectParameter("p_addhoc_from_date", p_addhoc_from_date) :
                new ObjectParameter("p_addhoc_from_date", typeof(System.DateTime));
    
            var p_addhoc_to_dateParameter = p_addhoc_to_date.HasValue ?
                new ObjectParameter("p_addhoc_to_date", p_addhoc_to_date) :
                new ObjectParameter("p_addhoc_to_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("employee_recruit_insert", p_IdParameter, p_intv_noParameter, p_f_nameParameter, p_m_nameParameter, p_l_nameParameter, p_qualificationParameter, p_schoolParameter, p_adr1Parameter, p_adr2Parameter, p_adr3Parameter, p_st_noParameter, p_st_nameParameter, p_cityParameter, p_stateParameter, p_pinParameter, p_employment_typeParameter, p_interview_dateParameter, p_online_diary_noParameter, p_dispatch_noParameter, p_join_dateParameter, p_datedParameter, p_gen_applied_postParameter, p_gen_basic_payParameter, p_gen_pay_scale_levelParameter, p_gen_payscaleParameter, p_addhoc_net_salaryParameter, p_addhoc_tenureParameter, p_addhoc_from_dateParameter, p_addhoc_to_dateParameter);
        }
    
        public virtual int employee_recruit_update(string p_Id, Nullable<long> p_intv_no, string p_f_name, string p_m_name, string p_l_name, string p_qualification, string p_school, string p_adr1, string p_adr2, string p_adr3, string p_st_no, string p_st_name, string p_city, string p_state, string p_pin, string p_employment_type, Nullable<System.DateTime> p_interview_date, string p_online_diary_no, string p_dispatch_no, Nullable<System.DateTime> p_join_date, Nullable<System.DateTime> p_dated, string p_gen_applied_post, string p_gen_basic_pay, string p_gen_pay_scale_level, string p_gen_payscale, string p_addhoc_net_salary, string p_addhoc_tenure, Nullable<System.DateTime> p_addhoc_from_date, Nullable<System.DateTime> p_addhoc_to_date)
        {
            var p_IdParameter = p_Id != null ?
                new ObjectParameter("p_Id", p_Id) :
                new ObjectParameter("p_Id", typeof(string));
    
            var p_intv_noParameter = p_intv_no.HasValue ?
                new ObjectParameter("p_intv_no", p_intv_no) :
                new ObjectParameter("p_intv_no", typeof(long));
    
            var p_f_nameParameter = p_f_name != null ?
                new ObjectParameter("p_f_name", p_f_name) :
                new ObjectParameter("p_f_name", typeof(string));
    
            var p_m_nameParameter = p_m_name != null ?
                new ObjectParameter("p_m_name", p_m_name) :
                new ObjectParameter("p_m_name", typeof(string));
    
            var p_l_nameParameter = p_l_name != null ?
                new ObjectParameter("p_l_name", p_l_name) :
                new ObjectParameter("p_l_name", typeof(string));
    
            var p_qualificationParameter = p_qualification != null ?
                new ObjectParameter("p_qualification", p_qualification) :
                new ObjectParameter("p_qualification", typeof(string));
    
            var p_schoolParameter = p_school != null ?
                new ObjectParameter("p_school", p_school) :
                new ObjectParameter("p_school", typeof(string));
    
            var p_adr1Parameter = p_adr1 != null ?
                new ObjectParameter("p_adr1", p_adr1) :
                new ObjectParameter("p_adr1", typeof(string));
    
            var p_adr2Parameter = p_adr2 != null ?
                new ObjectParameter("p_adr2", p_adr2) :
                new ObjectParameter("p_adr2", typeof(string));
    
            var p_adr3Parameter = p_adr3 != null ?
                new ObjectParameter("p_adr3", p_adr3) :
                new ObjectParameter("p_adr3", typeof(string));
    
            var p_st_noParameter = p_st_no != null ?
                new ObjectParameter("p_st_no", p_st_no) :
                new ObjectParameter("p_st_no", typeof(string));
    
            var p_st_nameParameter = p_st_name != null ?
                new ObjectParameter("p_st_name", p_st_name) :
                new ObjectParameter("p_st_name", typeof(string));
    
            var p_cityParameter = p_city != null ?
                new ObjectParameter("p_city", p_city) :
                new ObjectParameter("p_city", typeof(string));
    
            var p_stateParameter = p_state != null ?
                new ObjectParameter("p_state", p_state) :
                new ObjectParameter("p_state", typeof(string));
    
            var p_pinParameter = p_pin != null ?
                new ObjectParameter("p_pin", p_pin) :
                new ObjectParameter("p_pin", typeof(string));
    
            var p_employment_typeParameter = p_employment_type != null ?
                new ObjectParameter("p_employment_type", p_employment_type) :
                new ObjectParameter("p_employment_type", typeof(string));
    
            var p_interview_dateParameter = p_interview_date.HasValue ?
                new ObjectParameter("p_interview_date", p_interview_date) :
                new ObjectParameter("p_interview_date", typeof(System.DateTime));
    
            var p_online_diary_noParameter = p_online_diary_no != null ?
                new ObjectParameter("p_online_diary_no", p_online_diary_no) :
                new ObjectParameter("p_online_diary_no", typeof(string));
    
            var p_dispatch_noParameter = p_dispatch_no != null ?
                new ObjectParameter("p_dispatch_no", p_dispatch_no) :
                new ObjectParameter("p_dispatch_no", typeof(string));
    
            var p_join_dateParameter = p_join_date.HasValue ?
                new ObjectParameter("p_join_date", p_join_date) :
                new ObjectParameter("p_join_date", typeof(System.DateTime));
    
            var p_datedParameter = p_dated.HasValue ?
                new ObjectParameter("p_dated", p_dated) :
                new ObjectParameter("p_dated", typeof(System.DateTime));
    
            var p_gen_applied_postParameter = p_gen_applied_post != null ?
                new ObjectParameter("p_gen_applied_post", p_gen_applied_post) :
                new ObjectParameter("p_gen_applied_post", typeof(string));
    
            var p_gen_basic_payParameter = p_gen_basic_pay != null ?
                new ObjectParameter("p_gen_basic_pay", p_gen_basic_pay) :
                new ObjectParameter("p_gen_basic_pay", typeof(string));
    
            var p_gen_pay_scale_levelParameter = p_gen_pay_scale_level != null ?
                new ObjectParameter("p_gen_pay_scale_level", p_gen_pay_scale_level) :
                new ObjectParameter("p_gen_pay_scale_level", typeof(string));
    
            var p_gen_payscaleParameter = p_gen_payscale != null ?
                new ObjectParameter("p_gen_payscale", p_gen_payscale) :
                new ObjectParameter("p_gen_payscale", typeof(string));
    
            var p_addhoc_net_salaryParameter = p_addhoc_net_salary != null ?
                new ObjectParameter("p_addhoc_net_salary", p_addhoc_net_salary) :
                new ObjectParameter("p_addhoc_net_salary", typeof(string));
    
            var p_addhoc_tenureParameter = p_addhoc_tenure != null ?
                new ObjectParameter("p_addhoc_tenure", p_addhoc_tenure) :
                new ObjectParameter("p_addhoc_tenure", typeof(string));
    
            var p_addhoc_from_dateParameter = p_addhoc_from_date.HasValue ?
                new ObjectParameter("p_addhoc_from_date", p_addhoc_from_date) :
                new ObjectParameter("p_addhoc_from_date", typeof(System.DateTime));
    
            var p_addhoc_to_dateParameter = p_addhoc_to_date.HasValue ?
                new ObjectParameter("p_addhoc_to_date", p_addhoc_to_date) :
                new ObjectParameter("p_addhoc_to_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("employee_recruit_update", p_IdParameter, p_intv_noParameter, p_f_nameParameter, p_m_nameParameter, p_l_nameParameter, p_qualificationParameter, p_schoolParameter, p_adr1Parameter, p_adr2Parameter, p_adr3Parameter, p_st_noParameter, p_st_nameParameter, p_cityParameter, p_stateParameter, p_pinParameter, p_employment_typeParameter, p_interview_dateParameter, p_online_diary_noParameter, p_dispatch_noParameter, p_join_dateParameter, p_datedParameter, p_gen_applied_postParameter, p_gen_basic_payParameter, p_gen_pay_scale_levelParameter, p_gen_payscaleParameter, p_addhoc_net_salaryParameter, p_addhoc_tenureParameter, p_addhoc_from_dateParameter, p_addhoc_to_dateParameter);
        }
    
        public virtual int user_delete(string p_id)
        {
            var p_idParameter = p_id != null ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("user_delete", p_idParameter);
        }
    
        public virtual int user_insert(string p_id, string p_f_name, string p_m_name, string p_l_name, string p_p_address, string p_l_address, string p_email, string p_phone)
        {
            var p_idParameter = p_id != null ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(string));
    
            var p_f_nameParameter = p_f_name != null ?
                new ObjectParameter("p_f_name", p_f_name) :
                new ObjectParameter("p_f_name", typeof(string));
    
            var p_m_nameParameter = p_m_name != null ?
                new ObjectParameter("p_m_name", p_m_name) :
                new ObjectParameter("p_m_name", typeof(string));
    
            var p_l_nameParameter = p_l_name != null ?
                new ObjectParameter("p_l_name", p_l_name) :
                new ObjectParameter("p_l_name", typeof(string));
    
            var p_p_addressParameter = p_p_address != null ?
                new ObjectParameter("p_p_address", p_p_address) :
                new ObjectParameter("p_p_address", typeof(string));
    
            var p_l_addressParameter = p_l_address != null ?
                new ObjectParameter("p_l_address", p_l_address) :
                new ObjectParameter("p_l_address", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_phoneParameter = p_phone != null ?
                new ObjectParameter("p_phone", p_phone) :
                new ObjectParameter("p_phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("user_insert", p_idParameter, p_f_nameParameter, p_m_nameParameter, p_l_nameParameter, p_p_addressParameter, p_l_addressParameter, p_emailParameter, p_phoneParameter);
        }
    
        public virtual int user_update(string p_id, string p_f_name, string p_m_name, string p_l_name, string p_p_address, string p_l_address, string p_email, string p_phone)
        {
            var p_idParameter = p_id != null ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(string));
    
            var p_f_nameParameter = p_f_name != null ?
                new ObjectParameter("p_f_name", p_f_name) :
                new ObjectParameter("p_f_name", typeof(string));
    
            var p_m_nameParameter = p_m_name != null ?
                new ObjectParameter("p_m_name", p_m_name) :
                new ObjectParameter("p_m_name", typeof(string));
    
            var p_l_nameParameter = p_l_name != null ?
                new ObjectParameter("p_l_name", p_l_name) :
                new ObjectParameter("p_l_name", typeof(string));
    
            var p_p_addressParameter = p_p_address != null ?
                new ObjectParameter("p_p_address", p_p_address) :
                new ObjectParameter("p_p_address", typeof(string));
    
            var p_l_addressParameter = p_l_address != null ?
                new ObjectParameter("p_l_address", p_l_address) :
                new ObjectParameter("p_l_address", typeof(string));
    
            var p_emailParameter = p_email != null ?
                new ObjectParameter("p_email", p_email) :
                new ObjectParameter("p_email", typeof(string));
    
            var p_phoneParameter = p_phone != null ?
                new ObjectParameter("p_phone", p_phone) :
                new ObjectParameter("p_phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("user_update", p_idParameter, p_f_nameParameter, p_m_nameParameter, p_l_nameParameter, p_p_addressParameter, p_l_addressParameter, p_emailParameter, p_phoneParameter);
        }
    }
}
